### ISSUE TITLE
Including the Moosic Yosys plugin for logic locking

### ISSUE THREAD

**Issue by Coloquinte** [YosysHQ/oss-cad-suite-build#106]
Hello!

I'm developing [Moosic](https://github.com/Coloquinte/moosic-yosys-plugin), a Yosys plugin for supply chain security. Would you be open to including it in OSS CAD Suite?

I can contribute the installation script, similar to what's done for the [GHDL](https://github.com/YosysHQ/oss-cad-suite-build/blob/master/default/scripts/ghdl-yosys-plugin.sh) plugin.

**Comment by mmicko** [comment]
Sorry for late reply, checked with few more people, but this is not something needed by average user of oss-cad-suite.
