### ISSUE TITLE
Hardcoded GHDL version number cause compiling to fail after recent update to GHDL v5 (darwin-x64 only)

### ISSUE THREAD

**Issue by consanii** [YosysHQ/oss-cad-suite-build#110]
Pretty much as description.
The scripts `ghdl.sh` and `ghdl-yosys-plugin.sh`, for the darwin-x64 architecture only, have hardcoded the GHDL version in all the paths that go and look for the file `libghdl-4_0_0_dev.dylib`. This cause the build to fail as now GHDL nightly development moved to version v5.0.0, and consequently the file is now called `libghdl-5_0_0_dev.dylib`.

**Comment by mmicko** [comment]
Sorry for making this one wait too long :(
