### ISSUE TITLE
VIRTUAL_ENV environment from env script needs to be a real path

### ISSUE THREAD

**Issue by vvuk** [YosysHQ/oss-cad-suite-build#114]
`pyenv`'s activate script sets `VIRTUAL_ENV` to the path to the venv, where as the oss-cad-suite one just sets it to `OSS CAD Suite`.  This means, at least, that VS Code can't figure out a python interpreter when the suite is active (though even that isn't sufficient, it seems). It should be set to the `oss-cad-suite` directory path.

**Comment by mmicko** [comment]
It is merged now, feel free to  ping me if it needs more tuning. I made sure we are now using other variables same as they so it should be more compatible

**Comment by vvuk** [comment]
хвала!
