### ISSUE TITLE
[FEATURE REQUEST] Add support for PowerShell on windows

### ISSUE THREAD

**Issue by jamon** [YosysHQ/oss-cad-suite-build#130]
It would be nice to support powershell / windows terminal on windows instead of just cmd.exe (via .bat file).

I'm including a Pull Request that adds this support.  I've validated that the `environment.ps1` powershell script I've created works as intended, but I cannot easily validate that the build process includes it as intended--so it would be helpful if a maintainer could take a peek at it and make sure that I did all the right things to get it included in the bundle for windows.

Let me know if you have any questions.

**Comment by mmicko** [comment]
Thanks. Tested and it works. Also latest build is already updated
