### ISSUE TITLE
Applications should not try to write in the install directory.

### ISSUE THREAD

**Issue by DaveDavenport** [YosysHQ/oss-cad-suite-build#26]
If you extract this build into a read-only directory almost everything works, except for gtkwave.
The GtkWave wrapper calls `gdk-pixbuf-query-loaders --update-cache` and this tries to update a file in release_topdir_abs.

This can be fixed by setting GDK_PIXBUF_MODULE_FILE= in the wrapper to a user writable location.

I (moved it lower) and set it to:

```bash
export GDK_PIXBUF_MODULE_FILE="$XDG_CACHE_HOME/loaders.cache"
```

**Comment by mmicko** [comment]
Thanks @DaveDavenport  for pointing to this, have to do more checks, to generate file if it does not exists and test it on other platform. Hope to have this in next couple of days.

**Comment by mmicko** [comment]
@DaveDavenport can you confirm it is working fine at your end ?

**Comment by DaveDavenport** [comment]
Just tested it, it seems to work. Thanks.

**Comment by mmicko** [comment]
Thanks
