### ISSUE TITLE
Add Verible suite

### ISSUE THREAD

**Issue by abderraouf-adjal** [YosysHQ/oss-cad-suite-build#31]
Hi,

This is a request/idea to add [Verible](https://github.com/chipsalliance/verible) (a suite of SystemVerilog developer tools, including a parser, style-linter, and formatter.)

Thanks.

**Comment by mmicko** [comment]
Verible is depending on bazel build system, that would be quite an effort to support to support in our cross compilation build system. Also seems quite not ready for production uses since version is still 0.0.xxxx.
