### ISSUE TITLE
Include Python headers for building wheels while installing packages if necessary

### ISSUE THREAD

**Issue by abhishek-kakkar** [YosysHQ/oss-cad-suite-build#37]
If a user wants to install Python libraries that require building wheels (or compilation of any kind), the install fails as it requires Python headers, which are not bundled in the build (or might be getting stripped in the packaging process).

For example, I was trying to update cocotb in the installed Python distribution, and it failed to locate <Python.h> while building its wheels. I had to manually download the Python 3.8 headers and add in the correct location to get it to build.

**Comment by mmicko** [comment]
This is now changed in build scripts, so there will be python3 headers available in release from next build.
