### ISSUE TITLE
support for iceprogduino

### ISSUE THREAD

**Issue by x653** [YosysHQ/oss-cad-suite-build#38]
Hi,
nice idea to bundle all open source projects concerned with digital logic design.
May I kindly ask you to add support for "iceprogduino"?
It is a programmer used for ice40HX-boards from Olimex.
The following repo contains two files:
iceprogduino.c and a Makefile.
So to install iceprogduino just cd into the directory and run make + sudo make install.

https://github.com/OLIMEX/iCE40HX1K-EVB/tree/master/programmer/iceprogduino

**Comment by mmicko** [comment]
Thanks for PR
