### ISSUE TITLE
doc: macos: additional step to remove com.apple.quarantine extended attribute

### ISSUE THREAD

**Issue by cfriedt** [YosysHQ/oss-cad-suite-build#40]
First I wanted to say thank you for making a macOS (Aarch64) OSS package 😄  And also hi 👋 big fan and thank you for all of your work in general 🙏 

I just wanted to make a minor suggestion - that you add this step to your macOS install documentation
```bash
sudo find /opt/oss-cad-suite  -type f -exec xattr -d com.apple.quarantine {} \;
```

If it's already mentioned, and I somehow missed it, please disregard. 

It needs to be done for every Mach-O file (executable or dyld) otherwise the macOS "gatekeeper" / "quarantine" refuses to execute code from those files.

**Comment by mmicko** [comment]
Thank you for kind words and feedback. Activation script is now there and new step is added in README.md (in next commit :) )
