### ISSUE TITLE
Unique link for newest release

### ISSUE THREAD

**Issue by splinedrive** [YosysHQ/oss-cad-suite-build#53]
Hi,

it would be nice to have an unique  link to get the latest tarball for an architecture.

**Comment by lethalbit** [comment]
The only reliable way to do this at the moment is to use the GitHub API with the `releases/latest` endpoint for the repository.

What would be use-case for such a link?

**Comment by lethalbit** [comment]
If you're going to use this with a GitHub CI Workflow, then I recommend using the [setup-oss-cad-suite](https://github.com/YosysHQ/setup-oss-cad-suite) action as it handles it all for you.
