### ISSUE TITLE
Verilator now supports cocotb

### ISSUE THREAD

**Issue by hakan-demirli** [YosysHQ/oss-cad-suite-build#56]
The latest Verilator 5.006 fixed the issue that caused problems with cocotb. 
SOURCE: https://github.com/verilator/verilator/issues/2778#issuecomment-1399500208

Can we have an updated build?
Also, README needs to be changed as well.
https://github.com/YosysHQ/oss-cad-suite-build/blob/61078090139f1dac2b8ec2029b5889acf7661b9c/README.md?plain=1#L76

**Comment by hakan-demirli** [comment]
My bad. I didn't notice the Github actions. It is automatically released.

**Comment by mmicko** [comment]
Thanks, updated README.md in https://github.com/YosysHQ/oss-cad-suite-build/commit/985352017c21f29455b1d1fd2bfc420c99be507a
