### ISSUE TITLE
support of RHEL7

### ISSUE THREAD

**Issue by cdorbell2** [YosysHQ/oss-cad-suite-build#57]
Hi all
do you known if the build work on rhel 7/8 ( Rocky 8 ) ?
the ESD alliance doesn't support ubuntu  https://www.semi.org/en/communities/esda/OSRoadmap

**Comment by mmicko** [comment]
Command line tools will work on any linux distribution since all requirements are in package.

**Comment by cdorbell2** [comment]
but the target linux-x64 is based for an ubuntu ?

**Comment by mmicko** [comment]
yes, but wrapper makes sure it is possible to execute binaries on other distributions as well
