### ISSUE TITLE
openFPGALoader in macOS M1 version has a bad path hardcoded (?) for SPI-over-JTAG flash programming

### ISSUE THREAD

**Issue by aspdigital** [YosysHQ/oss-cad-suite-build#62]
I'm working with a Spartan-7 device (for the time being on an Arty board), with an SPI flash for configuration. My specific version of the oss-cad-suite-build is 20230211, and I see there were issues building it later.

When I do 

`% openFPGALoader -b arty_s7_25 -f test_design.bit`

I get an error when it tries to load the SPI-programmer bit file:

```
write to flash
Jtag frequency : requested 6.00MHz   -> real 6.00MHz  
Open file DONE
Parse file DONE
use: /yosyshq/share/openFPGALoader/spiOverJtag_xc7s25csga324.bit.gz
Error: fail to open /yosyshq/share/openFPGALoader/spiOverJtag_xc7s25csga324.bit.gz
Error: Failed to program FPGA: Error: fail to open /yosyshq/share/openFPGALoader/spiOverJtag_xc7s25csga324.bit.gz

```
and it's obviously because I don't have the `/yosyshq/share/openFPGALoader` path.

The loader binary archive is in `/Applications/oss-cad-suite/share/openFPGALoader`

Is this an issue with how you're building this tool? Anything special I can do, short of downloading the source for it and building it separately?

**Comment by mmicko** [comment]
I have added issue on openFPGALoader https://github.com/trabucayre/openFPGALoader/issues/333, since location of files is hard coded when compiling, and currently can not be altered after, so requested feature to be able to do this.
