### ISSUE TITLE
ecpdap build fails, rustc version not up to date

### ISSUE THREAD

**Issue by wheresheisnt** [YosysHQ/oss-cad-suite-build#68]
Kia Ora,
Attempted a build of the suite as a stress test on Ubuntu 22.04.2 LTS x86-64 - the usual fun on a new system. 
The build for ecpdap fails due to a variety of dependencies being unable to compile due to the rustc version being at `1.62.1` where `1.64.0` or newer is required.

Below is a copy of the stdout. I'm not experienced enough with docker based builds to find where the rust installation comes from and rectify the issue unfortunately. Rustc as installed on the system is, according to `rustc --version`, `rustc 1.70.0 (90c541806 2023-05-31)`. 

Thanks everyone! I hope that this is useful.

```
==> Building ecpdap for linux-x64 architecture ...
==> Step [ 1/ 1] building ecpdap ...
  -> Remove old output dir ...
  -> Creating output dir ...
  -> Remove old build dir ...
  -> Creating build dir ...
  -> Copy 'ecpdap' source to build dir ...
  -> Compiling ...
+ export PKG_CONFIG_ALLOW_CROSS=YES
+ PKG_CONFIG_ALLOW_CROSS=YES
+ cargo install --no-track --path ecpdap --root /work/_outputs/linux-x64/ecpdap/yosyshq --target=x86_64-unknown-linux-gnu
  Installing ecpdap v0.2.0 (/work/_builds/linux-x64/ecpdap/ecpdap)
    Updating crates.io index
error: failed to compile `ecpdap v0.2.0 (/work/_builds/linux-x64/ecpdap/ecpdap)`, intermediate artifacts can be found at `/work/_builds/linux-x64/ecpdap/ecpdap/target`

Caused by:
  package `anstyle-parse v0.2.0` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.62.1

==> ERROR : Script returned error code 101.
```

**Comment by mmicko** [comment]
Thanks for report. Fixed with [7871f6e722a76aa20261c43a25ca3414c33b3ada](https://github.com/YosysHQ/oss-cad-suite-build/commit/7871f6e722a76aa20261c43a25ca3414c33b3ada)
